Allow quickfzf to be run wherever the VMs are (#32)
Also added a check that the user has quickemu installed.

Co-authored-by: zenobit <zen@osowoso.xyz>

diff --git a/quickfzf b/quickfzf
--- a/quickfzf
+++ b/quickfzf
@@ -2,7 +2,6 @@
 
 # Author: zenobit
 # Description: Uses fzf to provide a simple GUI for quickemu and quickget
-# script must be in same directory as quickget and quickemu!
 # License MIT
 
 # Define variables
@@ -18,6 +17,13 @@ trap "exit" EXIT
 if ! command -v fzf >/dev/null 2>&1; then
 	echo "You are missing fzf..." && exit 255
 fi
+
+if ! command -v quickemu >/dev/null 2>&1; then
+	echo "You are missing quickemu..." && exit 255
+fi
+
+QUICKGET=$(command -v quickget)   || exit 255
+
 # Display version and prepared VMs
 #printf " $progname: $version\n quickemu: $(quickemu --version)\n\n Prepared VMs:\n-------------\n"
 printf '%s: v.%s\nquickemu: v.%s\n\n Workdir: %s\n\n Prepared VMs:\n-------------\n' "$progname" "$version" "$(quickemu --version)" "$(pwd)"
@@ -55,9 +61,9 @@ Choose other language" | fzf --cycle)
 10
 11" | fzf --cycle)
 			# get window language list
-			wlend=$(($(cat quickget | sed '/Arabic/,$!d' | grep -n '}' | cut -d':' -f1 | head -n 1) - 1))
+			wlend=$(($(cat $QUICKGET  | sed '/Arabic/,$!d' | grep -n '}' | cut -d':' -f1 | head -n 1) - 1))
 			# get windows language
-			wlang=$(cat quickget | sed '/Arabic/,$!d' | head -n $wlend | cut -d'=' -f2 | tail -c +2 | head -c -2 | sed 's/^[ \t]*//' | fzf --cycle --header='Choose Language
+			wlang=$(cat $QUICKGET | sed '/Arabic/,$!d' | head -n $wlend | cut -d'=' -f2 | tail -c +2 | head -c -2 | sed 's/^[ \t]*//' | fzf --cycle --header='Choose Language
  or CTRL-c or ESC to quit')
 			# downloading windows
 			printf '\n Trying to download Windows %s %s...\n\n' "$wrelease" "$wlang"
