style(indentation): replace tabs with spaces

diff --git a/quickemu b/quickemu
--- a/quickemu
+++ b/quickemu
@@ -1842,13 +1842,13 @@ if [ -n "${VM}" ] && [ -e "${VM}" ]; then
     fi
 
     if [ -e "${disk_img}" ]; then
-		DiskChkMsg="$("$QEMU_IMG" check -q "${disk_img}" 2>&1)"
-		if [[ $DiskChkMsg ]]; then
-		    echo; echo "ERROR! disk.qcow2 has problems. Try qemu-img check --help."
-		    echo; echo "$DiskChkMsg" ; echo
-		    exit 1
-		fi
-	fi
+    DiskChkMsg="$("$QEMU_IMG" check -q "${disk_img}" 2>&1)"
+    if [[ $DiskChkMsg ]]; then
+        echo; echo "ERROR! disk.qcow2 has problems. Try qemu-img check --help."
+        echo; echo "$DiskChkMsg" ; echo
+        exit 1
+    fi
+  fi
 
     VMDIR=$(dirname "${disk_img}")
     VMNAME=$(basename "${VM}" .conf)
