added openbsd 7 support

diff --git a/quickget b/quickget
--- a/quickget
+++ b/quickget
@@ -7,6 +7,7 @@ function os_support() {
     linuxmint \
     lubuntu \
     macos \
+    openbsd \
     opensuse \
     ubuntu \
     ubuntu-budgie \
@@ -32,6 +33,10 @@ function releases_linuxmint(){
     echo cinnamon-20_2 \
     mate-20_2 \
     xfce-20-2
+}
+
+function releases_openbsd(){
+    echo 7_0
 }
 
 function releases_opensuse(){
@@ -361,6 +366,9 @@ function make_vm_config() {
     elif [[ "${OS}" == *"linuxmint"* ]]; then
         GUEST="linux"
         IMAGE_TYPE="iso"
+    elif [[ "${OS}" == "openbsd" ]]; then
+        GUEST="openbsd"
+        IMAGE_TYPE="iso"
     elif [[ "${OS}" == *"opensuse"* ]]; then
         GUEST="linux"
         IMAGE_TYPE="iso"
@@ -495,6 +503,29 @@ function get_linuxmint() {
     ISO="linuxmint-${VERSION}-${FLAVOR}-64bit.iso"
     URL="${DL_BASE}/${VERSION}/${ISO}"
 
+    make_vm_dir
+    web_get ${URL} ${VM_PATH}
+    make_vm_config ${ISO}
+    start_vm_info
+}
+
+function get_openbsd() {
+    local URL=""
+    local DL_BASE="https://cdn.openbsd.org/pub/OpenBSD/7.0/amd64/"
+    local VERSION=""
+
+    case ${RELEASE} in
+        7_0) VERSION=${RELEASE//_/};;
+        *)
+            echo "ERROR! OpenBSD ${RELEASE} is not a supported release."
+            releases_openbsd
+            exit 1
+            ;;
+    esac
+
+    URL="${DL_BASE}/install${VERSION}.iso"
+
+    ISO="install${VERSION}.iso"
     make_vm_dir
     web_get ${URL} ${VM_PATH}
     make_vm_config ${ISO}
@@ -768,6 +799,8 @@ else
         releases_linuxmint
     elif [ "${OS}" == "opensuse" ]; then
         releases_opensuse
+    elif [ "${OS}" == "openbsd" ]; then
+        releases_openbsd
     elif [ "${OS}" == "macos" ]; then
         releases_macos
     elif [[ "${OS}" == *"ubuntu"* ]]; then
@@ -788,6 +821,8 @@ elif [[ "${OS}" == *"fedora"* ]]; then
     get_fedora
 elif [[ "${OS}" == *"linuxmint"* ]]; then
     get_linuxmint
+elif [[ "${OS}" == *"openbsd" ]]; then
+    get_openbsd
 elif [[ "${OS}" == *"opensuse"* ]]; then
     get_opensuse
 elif [[ "${OS}" == *"ubuntu"* ]]; then
