Reworded OK to PASS, ERROR! to FAIL

diff --git a/quickget b/quickget
--- a/quickget
+++ b/quickget
@@ -417,7 +417,7 @@ function list_url_all() {
         if [[ $(type -t "editions_${OS}") == function ]]; then
             for OPTION in $(editions_"${OS}"); do
                 validate_release releases_"${OS}"
-                get_"${OS}" "${OPTION}" | cut_1 || echo "ERROR! - ${OS} ${RELEASE} ${OPTION}"
+                get_"${OS}" "${OPTION}" | cut_1 || echo "FAIL - ${OS} ${RELEASE} ${OPTION}"
             done
         elif [[ "${OS}" == "windows"* ]]; then
             "languages_${OS}"
@@ -429,16 +429,16 @@ function list_url_all() {
         #TODO NEEDED?
         elif [[ "${OS}" == "macos" ]]; then
             validate_release releases_"${OS}"
-            get_macos || echo "ERROR! - ${OS} ${RELEASE} ${OPTION}"
+            get_macos || echo "FAIL - ${OS} ${RELEASE} ${OPTION}"
         elif [[ "${OS}" == *ubuntu-server* ]]; then
             validate_release releases_ubuntu
-            get_ubuntu-server || echo "ERROR! - ${OS} ${RELEASE}"
+            get_ubuntu-server || echo "FAIL - ${OS} ${RELEASE}"
         elif [[ "${OS}" == *ubuntu* ]]; then
             validate_release releases_ubuntu
-            get_ubuntu || echo "ERROR! - ${OS} ${RELEASE}"
+            get_ubuntu || echo "FAIL - ${OS} ${RELEASE}"
         else
             validate_release releases_"${OS}"
-            get_"${OS}" "${RELEASE}" | cut_1 || echo "ERROR! - ${OS} ${RELEASE}"
+            get_"${OS}" "${RELEASE}" | cut_1 || echo "FAIL - ${OS} ${RELEASE}"
         fi
     done
     exit 0
@@ -487,10 +487,10 @@ function list_check_all() {
             GOOD=$(web_check "${URL}" && echo 'PASS' || echo 'FAIL')
         fi
 
-        if [[ "${GOOD}" == "OK" ]]; then
-            echo "OK - ${OS} ${RELEASE} ${OPTION} ${URL}"
+        if [[ "${GOOD}" == "PASS" ]]; then
+            echo "PASS - ${OS} ${RELEASE} ${OPTION} ${URL}"
         else
-            echo "ERROR - ${OS} ${RELEASE} ${OPTION} ${URL}"
+            echo "FAIL - ${OS} ${RELEASE} ${OPTION} ${URL}"
         fi
     done
     exit 0
