Use wget2 whenever available

diff --git a/quickget b/quickget
--- a/quickget
+++ b/quickget
@@ -939,12 +939,6 @@ function web_get() {
       exit 1
     fi
 
-    if wget --help | grep -q Wget2; then
-        local WGET_PROGRESS="--force-progress"
-    else   
-        local WGET_PROGRESS="--show-progress"
-    fi
-
     if command -v aria2c &>/dev/null; then
         if ! aria2c --stderr -x16 --continue=true --summary-interval=0 --download-result=hide --console-log-level=error "${URL}" --dir "${DIR}" -o "${FILE}"; then
           echo #Necessary as aria2c in suppressed mode does not have new lines
@@ -952,7 +946,12 @@ function web_get() {
           exit 1
         fi
         echo #Necessary as aria2c in suppressed mode does not have new lines
-    elif ! wget --quiet --continue --tries=3 --read-timeout=10 "${WGET_PROGRESS}" --progress=bar:force:noscroll "${URL}" -O "${DIR}/${FILE}"; then
+    elif command -v wget2 &>/dev/null; then
+        if ! wget2 --quiet --continue --tries=3 --read-timeout=10 --force-progress --progress=bar:force:noscroll "${URL}" -O "${DIR}/${FILE}"; then
+            echo "ERROR! Failed to download ${URL} with wget2. Try running 'quickget' again."
+            exit 1
+        fi
+    elif ! wget --quiet --continue --tries=3 --read-timeout=10 --show-progress --progress=bar:force:noscroll "${URL}" -O "${DIR}/${FILE}"; then
         echo "ERROR! Failed to download ${URL} with wget. Try running 'quickget' again."
         exit 1
     fi
