Not yet able to cache windows because windows

diff --git a/quickget b/quickget
--- a/quickget
+++ b/quickget
@@ -537,21 +537,26 @@ function check_hash() {
 }
 
 function copy_local(){
-  if [ -n "${ISODIR}" ]; then
-    # use supplied filename or default to original distro ISO name
-      if [ -z "${LOCALISO}" ]; then
-        LOCALISO=${FILE}
-      fi
-      LOCALFILE=$(find "${ISODIR}" -type f -name "${LOCALISO}" -print -quit )
-      if [ -f "${DIR}/${FILE}" ]; then
-        echo "ERROR! File Exists - not copying over local file"
-        echo "Move it out of the way to replace it with a local file"
-        exit 1
-      else
-        cp -pv "${LOCALFILE}" "${DIR}"/"${FILE}"
-      # if ! ; then echo ERROR! Failed to copy ${LOCALFILE}" to ${DIR}/${FILE}"
-      fi
-    fi
+  case $OS in
+    windows)
+      echo "${OS} not (yet?)  supported for local isos" ;;
+    *)
+      if [ -n "${ISODIR}" ]; then
+        # use supplied filename or default to original distro ISO name
+          if [ -z "${LOCALISO}" ]; then
+            LOCALISO=${FILE}
+          fi
+          LOCALFILE=$(find "${ISODIR}" -type f -name "${LOCALISO}" -print -quit )
+          if [ -f "${DIR}/${FILE}" ]; then
+            echo "ERROR! File Exists - not copying over local file"
+            echo "Move it out of the way to replace it with a local file"
+            exit 1
+          else
+            cp -pv "${LOCALFILE}" "${DIR}"/"${FILE}"
+          # if ! ; then echo ERROR! Failed to copy ${LOCALFILE}" to ${DIR}/${FILE}"
+          fi
+        fi
+      esac
 }
 
 function web_get() {
