refactor: make test output in web_get() consistent with other tests

diff --git a/quickget b/quickget
--- a/quickget
+++ b/quickget
@@ -1270,8 +1270,8 @@ function web_get() {
         echo "${URL}"
         exit 0
     elif [ "${just}" == 'test' ]; then
-        echo -n "Testing if $(echo "${URL}" | rev | cut -d'/' -f1 | rev) is available... "
-        web_check "${URL}" && echo 'PASS' || echo 'FAIL'
+        GOOD=$(web_check "${URL}" && echo 'PASS' || echo 'FAIL')
+        echo -e "${GOOD}:\t${OS}\t${RELEASE}\t${EDITION}\t${URL}"
         exit 0
     elif [ "${just}" == 'download' ]; then
         DIR="$(pwd)"
