Merged macrecovery functions into quickget. Chunkcheck (C) to replace macrecovery's image verification Chunkcheck written by MCJack123: https://gist.github.com/MCJack123/943eaca762730ca4b7ae460b731b68e7

diff --git a/quickget b/quickget
--- a/quickget
+++ b/quickget
@@ -175,7 +175,7 @@ function list_csv() {
 
     for RELEASE in $("releases_${FUNC}"); do
       if [ "${OS}" == "macos" ]; then
-        DOWNLOADER="macrecovery"
+        DOWNLOADER="wget"
       elif [[ "${OS}" == *"ubuntu"* ]] && [ "${RELEASE}" == "devel" ] && [ ${HAS_ZSYNC} -eq 1 ]; then
         DOWNLOADER="zsync"
       else
@@ -1624,10 +1624,29 @@ function get_lmde() {
     echo "${URL}/${ISO} ${HASH}"
 }
 
+function save_macos_image() {
+    local url="${1}"
+    local session="${2}"
+    local outpath="${3}"
+    wget --quiet --continue --tries=3 --read-timeout=10 --show-progress --progress=bar:force:noscroll \
+    --header "Host: oscdn.apple.com" --header "Connection: close" --header "User-Agent: InternetRecovery/1.0" \
+    --header "Cookie: AssetToken=${session}" "${url}" -O "${outpath}"
+}
+
+function generate_id() {
+    local macRecoveryID=""
+    type="${1}"
+    local valid_chars=("0" "1" "2" "3" "4" "5" "6" "7" "8" "9" "A" "B" "C" "D" "E" "F")
+    for ((i=0; i<$type; i++)); do
+        macRecoveryID+=$(echo -n ${valid_chars[$((RANDOM % 16))]})
+    done
+    echo "${macRecoveryID}"
+}
+
 function get_macos() {
     local BOARD_ID=""
     local CWD=""
-    local MACRECOVERY=""
+    local CHUNKCHECK=""
     local MLB="00000000000000000"
     local OS_TYPE="default"
 
@@ -1669,36 +1688,41 @@ function get_macos() {
            exit 1;;
     esac
 
-    # Use a bundled macrecovery if possible
+    # Use a bundled chunkcheck if possible
     CWD="$(dirname "${0}")"
-    if [ -x "${CWD}/macrecovery" ]; then
-        MACRECOVERY="${CWD}/macrecovery"
-    elif [ -x /usr/bin/macrecovery ]; then
-        MACRECOVERY="/usr/bin/macrecovery"
+    if [ -x "${CWD}/chunkcheck" ]; then
+        CHUNKCHECK="${CWD}/chunkcheck"
     else
-        web_get "https://raw.githubusercontent.com/wimpysworld/quickemu/master/macrecovery" "${HOME}/.quickemu"
-        MACRECOVERY="python3 ${HOME}/.quickemu/macrecovery"
+        web_get "https://raw.githubusercontent.com/wimpysworld/quickemu/master/chunkcheck" "${HOME}/.quickemu"
+        CHUNKCHECK="${HOME}/.quickemu/chunkcheck"
     fi
 
-    if [ -z "${MACRECOVERY}" ]; then
-        echo "ERROR! Can not find a usable macrecovery."
-        exit 1
+    if [ -z "${CHUNKCHECK}" ]; then
+        read -p "ERROR! Can not find chunkcheck. Will not be able to verify image. Proceed anyways?" skipVerification 
+        if [ "${skipVerification,,}" != "y" ] && [ "${skipVerification,,}" != "yes" ]; then
+            exit 1
+        fi
+        echo 'Skipping verification' && skipVerification=true
     fi
 
     OpenCore_qcow2="https://github.com/kholia/OSX-KVM/raw/master/OpenCore/OpenCore.qcow2"
     OVMF_CODE="https://github.com/kholia/OSX-KVM/raw/master/OVMF_CODE.fd"
     OVMF_VARS="https://github.com/kholia/OSX-KVM/raw/master/OVMF_VARS-1920x1080.fd"
 
+    local appleSession=$(curl -v -H "Host: osrecovery.apple.com" -H "Connection: close" -A "InternetRecovery/1.0" http://osrecovery.apple.com/ 2>&1 | tr ';' '\n' | awk -F'session=|;' '{print $2}' | grep 1)
+    local info=$(curl -s -X POST -H "Host: osrecovery.apple.com" -H "Connection: close" -A "InternetRecovery/1.0" -b "session=\"${appleSession}\"" -H "Content-Type: text/plain"\
+    -d $'cid='$(generate_id 16)$'\nsn='${MLB}$'\nbid='${BOARD_ID}$'\nk='$(generate_id 64)$'\nfg='$(generate_id 64)$'\nos='${OS_TYPE} \
+    http://osrecovery.apple.com/InstallationPayload/RecoveryImage | tr ' ' '\n')
+    local downloadLink=$(echo "$info" | grep 'oscdn' | grep 'dmg')
+    local downloadSession=$(echo "$info" | grep 'expires' | grep 'dmg')
+
 	if [ "${show_iso_url}" == 'on' ]; then
-        RECOVERY_URL=$(${MACRECOVERY} --board-id "${BOARD_ID}" --mlb "${MLB}" --os-type "${OS_TYPE}" --basename RecoveryImage --outdir /dev/null \download 2>/dev/null | grep 'Saving' | cut -d' ' -f2)
-	    echo -e 'Recovery URL (inaccessible through normal browser):\n'"${RECOVERY_URL}"'\nFirmware URLs:\n'"${OpenCore_qcow2}\n${OVMF_CODE}\n${OVMF_VARS}"
+	    echo -e 'Recovery URL (inaccessible through normal browser):\n'"${downloadLink}"'\nFirmware URLs:\n'"${OpenCore_qcow2}\n${OVMF_CODE}\n${OVMF_VARS}"
 	    exit 0
     elif [ "${test_iso_url}" == 'on' ]; then
-        RECOVERY_URL=$(${MACRECOVERY} --board-id "${BOARD_ID}" --mlb "${MLB}" --os-type "${OS_TYPE}" --basename RecoveryImage --outdir /dev/null \download 2>/dev/null | grep 'Saving' | cut -d' ' -f2)
+
 	    wget --spider "${OpenCore_qcow2}" "${OVMF_CODE}" "${OVMF_VARS}"
-        echo Unable to test recovery image.
-        # This requires the "sess" variable to be populated. Would essentially require macrecovery to be completely rewritten within quickget. 
-        # wget -d --spider --header "'Host': purl.hostname" --header "'Connection': 'close'" --header "'User-Agent': 'InternetRecovery/1.0'" --header "'Cookie': '='.join(['AssetToken', ${sess}])" "${RECOVERY_URL}"
+        wget --spider --header "Host: oscdn.apple.com" --header "Connection: close" --header "User-Agent: InternetRecovery/1.0" --header "Cookie: AssetToken=${downloadSession}" "${downloadLink}"
 	    exit 0
     fi
 
@@ -1712,13 +1736,19 @@ function get_macos() {
 
     if [ ! -e "${VM_PATH}/RecoveryImage.chunklist" ]; then
         echo "Downloading macOS ${RELEASE}..."
-        ${MACRECOVERY} \
-            --board-id "${BOARD_ID}" \
-            --mlb "${MLB}" \
-            --os-type "${OS_TYPE}" \
-            --basename RecoveryImage \
-            --outdir "${VM_PATH}" \
-            download
+        local chunkListLink=$(echo "$info" | grep 'oscdn' | grep 'chunklist')
+        local chunkListSession=$(echo "$info" | grep 'expires' | grep 'chunklist')
+        save_macos_image "${downloadLink}" "${downloadSession}" "${VM_PATH}/RecoveryImage.dmg"
+        save_macos_image "${chunkListLink}" "${chunkListSession}" "${VM_PATH}/RecoveryImage.chunklist"
+    fi
+
+    echo "Verifying downloaded macOS ${RELEASE} image using chunklist."
+    if [ skipVerification != true ]; then
+        ${CHUNKCHECK} check "${VM_PATH}/RecoveryImage.chunklist" "${VM_PATH}/RecoveryImage.dmg"
+        if [ $? -ne 0 ]; then
+            echo "ERROR! Verification failed."
+            exit 1
+        fi
     fi
 
     if [ -e "${VM_PATH}/RecoveryImage.dmg" ] && [ ! -e "${VM_PATH}/RecoveryImage.img" ]; then
