Add FreeBSD support (#62)
* Add releases_freebsd() function

* complete FreeBSD addition

* Add README.md info for FreeBSD

Co-authored-by: Kai Lyons <kailyons@pop-os.localdomain>

diff --git a/quickget b/quickget
--- a/quickget
+++ b/quickget
@@ -1,7 +1,8 @@
 #!/usr/bin/env bash
 
 function os_support() {
-    echo kubuntu \
+    echo freebsd \
+    kubuntu \
     lubuntu \
     macos \
     ubuntu \
@@ -11,6 +12,12 @@ function os_support() {
     ubuntu-studio \
     windows \
     xubuntu
+}
+
+function releases_freebsd(){
+    echo 13_0 \
+    12_2 # replace with 12.3 upon release
+    # 14_0 # Waiting for 14.0 release
 }
 
 function releases_macos() {
@@ -128,7 +135,10 @@ function make_vm_config() {
     local GUEST=""
     IMAGE_FILE="${1}"
     ISO_FILE="${2}"
-    if [[ "${OS}" == *"ubuntu"* ]]; then
+    if [[ "${OS}" == "freebsd" ]]; then
+        GUEST="freebsd"
+        IMAGE_TYPE="iso"
+    elif [[ "${OS}" == *"ubuntu"* ]]; then
         GUEST="linux"
         IMAGE_TYPE="iso"
     elif [ "${OS}" == "macos" ]; then
@@ -166,6 +176,39 @@ function start_vm_info() {
     echo "To start your ${OS} ${RELEASE} virtual machine run:"
     echo "    quickemu --vm ${OS}-${RELEASE}.conf"
     echo
+}
+
+function get_freebsd() {
+    # For future releases, use dvd1 iso files.
+    local URL=""
+    local CHECKSUMS=""
+    local DL_BASE="https://download.freebsd.org/ftp/releases/amd64/amd64/ISO-IMAGES"
+    local VERSION=""
+    case ${RELEASE} in
+        13_0)
+            VERSION="13.0"
+        ;;
+        12_2)
+            VERSION="12.2"
+        ;;
+        # Waiting until FreeBSD 14 release
+        # 14_0)
+        #     VERSION="14.0"
+        # ;;
+        *)
+            echo "ERROR! FreeBSD ${RELEASE} is not a supported release."
+            releases_freebsd
+            exit 1
+        ;;
+    esac
+
+    URL="${DL_BASE}/${VERSION}/FreeBSD-${VERSION}-RELEASE-amd64-dvd1.iso"
+
+    ISO="FreeBSD-${VERSION}-RELEASE-amd64-dvd1.iso"
+    web_get ${URL} ${VM_PATH}
+    make_vm_dir
+    make_vm_config ${ISO}
+    start_vm_info
 }
 
 function get_macos() {
@@ -380,6 +423,8 @@ VM_PATH="${OS}-${RELEASE}"
 
 if [ "${OS}" == "macos" ]; then
     get_macos
+elif [[ "${OS}" == *"freebsd" ]]; then
+    get_freebsd
 elif [[ "${OS}" == *"ubuntu"* ]]; then
     get_ubuntu
 elif [ "${OS}" == "windows" ]; then
