add disk health check

diff --git a/quickemu b/quickemu
--- a/quickemu
+++ b/quickemu
@@ -1731,6 +1731,14 @@ if [ -n "${VM}" ] && [ -e "${VM}" ]; then
     exit 1
   fi
 
+  DiskCheck="$(qemu-img check -q "${disk_img}" 2>&1)"
+
+  if [[ $DiskCheck ]]; then
+    echo; echo "ERROR! disk.qcow2 has problems. Try qemu-img check --help."
+    echo; echo "$DiskCheck" ; echo
+    exit 1
+  fi
+
   VMDIR=$(dirname "${disk_img}")
   VMNAME=$(basename "${VM}" .conf)
   VMPATH=$(realpath "$(dirname "${VM}")")
