feat: Add function to show error message if path not specified

diff --git a/quickget b/quickget
--- a/quickget
+++ b/quickget
@@ -3443,6 +3443,12 @@ fi
 
 LANGS=()
 
+os_path_error() {
+    echo "ERROR! You must specify path."
+    os_error
+    exit 1
+}
+
 if [ -n "${1}" ]; then
     OS="${1,,}"
     if [ "${OS}" == "list" ] || [ "${OS}" == "list_csv" ]; then
