fix and skip windows test

diff --git a/quickget b/quickget
--- a/quickget
+++ b/quickget
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 #shellcheck disable=SC1001,1003,1083,2016,2046,2086,2155,2206,2207,2068,2071,2076,2162,2317
 export LC_ALL=C
+#set -x
 
 # Here the quick 'n dirty guide to adding a new OS to quickget
 #
@@ -30,6 +31,11 @@ function cleanup() {
     if [ -n "$(jobs -p)" ]; then
         kill "$(jobs -p)"
     fi
+}
+
+# Get string before first whitespace (HASH)
+function cut_1() {
+    cut -d' ' -f1
 }
 
 function os_info() {
@@ -293,6 +299,8 @@ list_supported() {
 }
 
 list_isos() {
+    local showIsoUrl=on
+    local DIR="/dev/null"
     local URL
     local FUNC
     local OPTION
@@ -305,24 +313,32 @@ list_isos() {
           *) FUNC="${OS}";;
         esac
         for RELEASE in $("releases_${FUNC}" | sed -Ee 's/eol-\S+//g' ); do # hide eol releases
+
             # If the OS has an editions_() function, use it.
             if [[ $(type -t "editions_${OS}") == function ]]; then
                 for OPTION in $(editions_"${OS}"); do
                     validate_release releases_${OS}
-                    get_${OS} ${OPTION} | cut_1
+                    get_${OS} ${OPTION} | cut_1 || echo "${OS} ${RELEASE} ${OPTION} ERROR!"
                 done
             elif [[ "${OS}" == "windows"* ]]; then
                 "languages_${OS}"
                 for OPTION in "${LANGS[@]}"; do
-                    validate_release releases_${OS}
-                    get_${OS} ${OPTION} | cut_1
+                    echo "skipped: ${OS} ${RELEASE} ${OPTION}"
+                    #validate_release releases_${OS}
+                    #get_${OS} ${OPTION} | cut_1
                 done
             #TODO NEEDED?
             elif [[ "${OS}" == "macos" ]]; then
                 echo "${OS}|${RELEASE}|${OPTION}|"
+            elif [[ "${OS}" == *"ubuntu"* ]]; then
+                validate_release releases_ubuntu
+                get_ubuntu || echo "${OS} ${RELEASE} ERROR!"
+            elif [[ "${OS}" == *"ubuntu-server"* ]]; then
+                validate_release releases_ubuntu
+                get_ubuntu-server || echo "${OS} ${RELEASE} ERROR!"
             else
                 validate_release releases_${OS}
-                get_${OS} ${RELEASE} | cut_1
+                get_${OS} ${RELEASE} | cut_1 || echo "${OS} ${RELEASE} ERROR!"
             fi
         done
     done
@@ -330,7 +346,7 @@ list_isos() {
 }
 
 test_isos() {
-    local test_iso_url="1"
+    local showIsoUrl=on
     local DIR="/dev/null"
     local FUNC
     local OPTION
@@ -339,16 +355,17 @@ test_isos() {
     check_it() {
         validate_release releases_${OS}
         URL=$(get_${OS} ${OPTION} | cut_1)
-        GOOD=$(wget -q --spider ${URL} && echo 'OK' || echo 'ERROR!')
+        GOOD=$(timeout 3 wget -q --spider ${URL} && echo 'OK' || echo 'ERROR!')
         if [[ "${GOOD}" == "OK" ]]; then
-            echo "OK - ${OS},${RELEASE},${OPTION},${URL}"
+            echo "OK - ${OS} ${RELEASE} ${OPTION} ${URL}"
         else
-            echo "ERROR - ${OS},${RELEASE},${OPTION},${URL}"
+            echo "ERROR - ${OS} ${RELEASE} ${OPTION} ${URL}"
         fi
     }
 
     for OS in $(os_support); do
-        case ${OS} in
+        local GOOD=""
+        case "${OS}" in
           *ubuntu-server*) FUNC="ubuntu-server";;
           *ubuntu*) FUNC="ubuntu";;
           *) FUNC="${OS}";;
@@ -360,18 +377,37 @@ test_isos() {
                     check_it
                 done
             elif [[ "${OS}" == "windows"* ]]; then
+                # skipping because of microsoft
                 "languages_${OS}"
                 for OPTION in "${LANGS[@]}"; do
-                    check_it
+                    echo "skipped: ${OS} ${RELEASE} ${OPTION}"
                 done
+            elif [[ "${OS}" == *"ubuntu"* ]]; then
+                #validate_release releases_ubuntu
+                URL=$(get_ubuntu)
+                GOOD=$(timeout 3 wget -q --spider ${URL} && echo 'OK' || echo 'ERROR!')
+                if [[ "${GOOD}" == "OK" ]]; then
+                    echo "OK - ${OS} ${RELEASE} ${URL}"
+                else
+                    echo "ERROR - ${OS} ${RELEASE} ${URL}"
+                fi
+            elif [[ "${OS}" == *"ubuntu-server"* ]]; then
+                #validate_release releases_ubuntu
+                URL="$(get_ubuntu-server)"
+                GOOD=$(timeout 3 wget -q --spider ${URL} && echo 'OK' || echo 'ERROR!')
+                if [[ "${GOOD}" == "OK" ]]; then
+                    echo "OK - ${OS} ${RELEASE} ${URL}"
+                else
+                    echo "ERROR - ${OS} ${RELEASE} ${URL}"
+                fi
             else
                 validate_release releases_${OS}
                 URL=$(get_${OS} ${RELEASE} | cut_1)
-                GOOD=$(wget -q --spider ${URL} && echo 'OK' || echo 'ERROR!')
+                GOOD=$(timeout 3 wget -q --spider ${URL} && echo 'OK' || echo 'ERROR!')
                 if [[ "${GOOD}" == "OK" ]]; then
-                    echo "OK - ${OS},${RELEASE},,${URL}"
+                    echo "OK - ${OS} ${RELEASE} ${URL}"
                 else
-                    echo "ERROR - ${OS},${RELEASE},,${URL}"
+                    echo "ERROR - ${OS} ${RELEASE} ${URL}"
                 fi
             fi
         done
@@ -476,11 +512,6 @@ function os_support() {
     xerolinux \
     xubuntu \
     zorin
-}
-
-# Get string before first whitespace (HASH)
-function cut_1() {
-    cut -d' ' -f1
 }
 
 function releases_alma() {
@@ -1136,7 +1167,7 @@ function check_hash() {
     local iso=""
     local hash=""
     local hash_algo=""
-    if [ "${download_iso}" == 1 ]; then
+    if [ "${downloadIso}" == on ]; then
         iso="${1}"
     else
         iso="${VM_PATH}/${1}"
@@ -1193,14 +1224,14 @@ function web_get() {
     done
 
     # Test mode for ISO
-    if [ "${show_iso_url}" == on ]; then
+    if [ "${showIsoUrl}" == on ]; then
         echo "${URL}"
         exit 0
-    elif [ "${test_iso_url}" == on ]; then
+    elif [ "${testIsoUrl}" == on ]; then
         echo -n "Testing if $(echo ${URL} | rev | cut -d'/' -f1 | rev) is available... "
         wget -q --spider "${URL}" && echo 'Sucessfull' || echo 'ERROR!'
         exit 0
-    elif [ "${download_iso}" == on ]; then
+    elif [ "${downloadIso}" == on ]; then
         DIR="$(pwd)"
     fi
 
@@ -1240,10 +1271,10 @@ function zsync_get() {
     local URL="${1}"
 
     # Test mode for ISO
-    if [ "${show_iso_url}" == 1 ]; then
+    if [ "${showIsoUrl}" == on ]; then
         echo "${URL}"
         exit 0
-    elif [ "${test_iso_url}" == 1 ]; then
+    elif [ "${testIsoUrl}" == on ]; then
         wget --spider "${URL}"
         exit 0
     elif command -v zsync &>/dev/null; then
@@ -1287,7 +1318,7 @@ function make_vm_config() {
     #not needed anymore?
     #local SEC_BOOT=""
 
-    if [ "${download_iso}" == 1 ]; then
+    if [ "${downloadIso}" == on ]; then
         exit 0
     fi
 
@@ -2178,14 +2209,14 @@ function get_macos() {
     local chunkListLink=$(echo "$info" | grep 'oscdn' | grep 'chunklist')
     local chunkListSession=$(echo "$info" | grep 'expires' | grep 'chunklist')
 
-    if [ "${show_iso_url}" == 1 ]; then
+    if [ "${showIsoUrl}" == on ]; then
         echo -e "Recovery URL (inaccessible through normal browser):\n${downloadLink}\nChunklist (used for verifying the Recovery Image):\n${chunkListLink}\nFirmware URLs:\n${OpenCore_qcow2}\n${OVMF_CODE}\n${OVMF_VARS}"
         exit 0
-    elif [ "${test_iso_url}" == 1 ]; then
+    elif [ "${testIsoUrl}" == on ]; then
         wget --spider --header "Host: oscdn.apple.com" --header "Connection: close" --header "User-Agent: InternetRecovery/1.0" --header "Cookie: AssetToken=${downloadSession}" "${downloadLink}"
         wget --spider --header "Host: oscdn.apple.com" --header "Connection: close" --header "User-Agent: InternetRecovery/1.0" --header "Cookie: AssetToken=${chunkListSession}" "${chunkListLink}"
         exit 0
-    elif [ "${download_iso}" == 1 ]; then
+    elif [ "${downloadIso}" == on ]; then
         echo "Downloading macOS ${RELEASE} from ${downloadLink}"
         web_get "${downloadLink}" "${VM_PATH}" RecoveryImage.dmg --header "Host: oscdn.apple.com" --header "Connection: close" --header "User-Agent: InternetRecovery/1.0" --header "Cookie: AssetToken=${downloadSession}"
         curl --progress-bar "${chunkListLink}" -o RecoveryImage.chunklist --header "Host: oscdn.apple.com" --header "Connection: close" --header "User-Agent: InternetRecovery/1.0" --header "Cookie: AssetToken=${chunkListSession}"
@@ -3338,7 +3369,7 @@ function download_windows() {
     fi
 
     if echo "$iso_download_link_html" | grep -q "We are unable to complete your request at this time."; then
-        if [ "${show_iso_url}" == 1 ] || [ "${test_iso_url}" == 1 ]; then
+        if [ "${showIsoUrl}" == on ] || [ "${testIsoUrl}" == on ]; then
             echo " - Failed to get URL: Microsoft blocked the automated download request based on your IP address."
             exit 1
         fi
@@ -3365,10 +3396,10 @@ function download_windows() {
         return 1
     fi
 
-    if [ "${show_iso_url}" == 1 ]; then
+    if [ "${showIsoUrl}" == on ]; then
         echo -e "   Windows ${RELEASE} Download (valid for 24 hours):\n${iso_download_link}"
         exit 0
-    elif [ "${test_iso_url}" == 1 ]; then
+    elif [ "${testIsoUrl}" == on ]; then
         wget --spider "${iso_download_link}"
         exit 0
     fi
@@ -3397,11 +3428,11 @@ function get_windows() {
         download_windows "${RELEASE}"
     fi
 
-    if [ "${download_iso}" == 1 ]; then
+    if [ "${downloadIso}" == on ]; then
         exit 0
     fi
 
-    if [ "${download_iso}" == 'on' ]; then
+    if [ "${downloadIso}" == on ]; then
         exit 0
     fi
 
@@ -3684,30 +3715,24 @@ case "${1}" in
   '-h'|'--help')
     help_message
     ;;
-  '-lc'|'list'|'list_csv')
+  '-lc'|'--list-csv')
     list_csv
     ;;
-  '-lj'|'list_json')
+  '-lj'|'--list-json')
     list_json
     ;;
   '-ls'|'--list-supported')
-    list_supported  
+    time list_supported
     ;;
   '-li'|'--list-isos')
-    list_isos
-    ;;  
+    time list_isos
+    ;;
   '-ti'|'--test-isos')
-    test_isos
+    time test_isos
     ;;
   '-d'|'--iso-download')
-    download_iso=1
-    if [ -n "$4" ]; then
-        set -- "$2" "$3" "$4"
-    elif [ -n "$3" ]; then
-        set -- "$2" "$3"
-    else
-        set -- "$2"
-    fi
+    downloadIso=on
+    shift
     ;;
   '-i'|'--os-info')
     echo "$(show_os_info "${2}")" | fold -s -w $(tput cols)
@@ -3745,7 +3770,6 @@ os_supported
 if [ -n "${2}" ]; then
     RELEASE="${2,,}"
     VM_PATH="${OS}-${RELEASE}"
-
     # If the OS has an editions_() function, use it.
     if [[ $(type -t "editions_${OS}") == function ]]; then
         validate_release "releases_${OS}"
@@ -3762,23 +3786,28 @@ if [ -n "${2}" ]; then
 
         VM_PATH="${OS}-${RELEASE}-${EDITION}"
         create_vm "$("get_${OS}" "${EDITION}")"
+
     elif [ "${OS}" == "macos" ]; then
         # macOS doesn't use create_vm()
         validate_release releases_macos
         get_macos
+
     elif [[ "${OS}" == *"ubuntu-server"* ]]; then
         # (Comes before regular Ubuntu, or the code tries to download the desktop) #
         # Ubuntu doesn't use create_vm()
         validate_release releases_ubuntu-server
         get_ubuntu-server
+
     elif [[ "${OS}" == *"ubuntu"* ]]; then
         # Ubuntu doesn't use create_vm()
         validate_release releases_ubuntu
         get_ubuntu
+
     elif [[ "${OS}" == *"deepin"* ]]; then
         # deepin doesn't use create_vm()
         validate_release releases_deepin
         get_deepin
+
     elif [[ "${OS}" == "windows"* ]]; then
         LANG="English International"
         "languages_${OS}"
@@ -3791,10 +3820,12 @@ if [ -n "${2}" ]; then
         fi
         validate_release "releases_${OS}"
         get_windows
+
     else
         validate_release "releases_${OS}"
         create_vm "$("get_${OS}")"
     fi
+
 elif [ $(releases_${OS} | wc -w) -eq 1 ] && [[ ! $(type -t "editions_${OS}") == function ]]; then
     RELEASE=$(releases_${OS})
     VM_PATH="${OS}"
