chore: Make indentation consistent

diff --git a/quickget b/quickget
--- a/quickget
+++ b/quickget
@@ -1074,7 +1074,7 @@ function editions_mxlinux(){
 }
 
 function releases_netboot() {
-  echo latest
+    echo latest
 }
 
 function releases_netbsd() {
@@ -1554,65 +1554,65 @@ function make_vm_config() {
     IMAGE_FILE="${1}"
     ISO_FILE="${2}"
     case "${OS}" in
-        batocera)
-            GUEST="batocera"
-            IMAGE_TYPE="img";;
-        dragonflybsd)
-            GUEST="dragonflybsd"
-            IMAGE_TYPE="iso";;
-        easyos)
-            GUEST="linux"
-            IMAGE_TYPE="img";;
-        freebsd|ghostbsd)
-            GUEST="freebsd"
-            IMAGE_TYPE="iso";;
-        haiku)
-            GUEST="haiku"
-            IMAGE_TYPE="iso";;
-        freedos)
-            GUEST="freedos"
-            IMAGE_TYPE="iso";;
-        kolibrios)
-            GUEST="kolibrios"
-            IMAGE_TYPE="iso";;
-        macos)
-            GUEST="macos"
-            IMAGE_TYPE="img";;
-        netbsd)
-            GUEST="netbsd"
-            IMAGE_TYPE="iso";;
-        openbsd)
-            GUEST="openbsd"
-            IMAGE_TYPE="iso";;
-        openindiana)
-            GUEST="solaris"
-            IMAGE_TYPE="iso";;
-        reactos)
-            GUEST="reactos"
-            IMAGE_TYPE="iso";;
-        truenas*)
-            GUEST="truenas"
-            IMAGE_TYPE="iso";;
-        ubuntu*)
-            GUEST="linux"
-            IMAGE_TYPE="iso"
-            # If there is a point in the release, check if it is less than 16.04
-            if [[ "${RELEASE}" == "*.*" ]]; then
-                local SHORT_RELEASE=${RELEASE//./}
-                if [ "${SHORT_RELEASE}" -lt 1604 ]; then
-                    GUEST="linux_old"
-                fi
+      batocera)
+        GUEST="batocera"
+        IMAGE_TYPE="img";;
+      dragonflybsd)
+        GUEST="dragonflybsd"
+        IMAGE_TYPE="iso";;
+      easyos)
+        GUEST="linux"
+        IMAGE_TYPE="img";;
+      freebsd|ghostbsd)
+        GUEST="freebsd"
+        IMAGE_TYPE="iso";;
+      haiku)
+        GUEST="haiku"
+        IMAGE_TYPE="iso";;
+      freedos)
+        GUEST="freedos"
+        IMAGE_TYPE="iso";;
+      kolibrios)
+        GUEST="kolibrios"
+        IMAGE_TYPE="iso";;
+      macos)
+        GUEST="macos"
+        IMAGE_TYPE="img";;
+      netbsd)
+        GUEST="netbsd"
+        IMAGE_TYPE="iso";;
+      openbsd)
+        GUEST="openbsd"
+        IMAGE_TYPE="iso";;
+      openindiana)
+        GUEST="solaris"
+        IMAGE_TYPE="iso";;
+      reactos)
+        GUEST="reactos"
+        IMAGE_TYPE="iso";;
+      truenas*)
+        GUEST="truenas"
+        IMAGE_TYPE="iso";;
+      ubuntu*)
+        GUEST="linux"
+        IMAGE_TYPE="iso"
+        # If there is a point in the release, check if it is less than 16.04
+        if [[ "${RELEASE}" == "*.*" ]]; then
+            local SHORT_RELEASE=${RELEASE//./}
+            if [ "${SHORT_RELEASE}" -lt 1604 ]; then
+                GUEST="linux_old"
             fi
-            ;;
-        windows)
-            GUEST="windows"
-            IMAGE_TYPE="iso";;
-        windows-server)
-            GUEST="windows-server"
-            IMAGE_TYPE="iso";;
-        *)
-            GUEST="linux"
-            IMAGE_TYPE="iso";;
+        fi
+        ;;
+      windows)
+        GUEST="windows"
+        IMAGE_TYPE="iso";;
+      windows-server)
+        GUEST="windows-server"
+        IMAGE_TYPE="iso";;
+      *)
+        GUEST="linux"
+        IMAGE_TYPE="iso";;
     esac
 
     CONF_FILE="${VM_PATH}.conf"
@@ -1932,26 +1932,26 @@ function get_crunchbang++() {
     local URLPART2=""
     URLPART="https://github.com/CBPP/cbpp"
     case ${RELEASE} in
-        8)
-            URLPART2="releases/download/v1.0-amd64"
-            ISO="cbpp-1.0-amd64-20150428.iso"
-            ;;
-        9)
-            URLPART2="9-amd64/releases/download/v9.0"
-            ISO="cbpp-9.0-amd64-20170621.iso"
-            ;;
-        10)
-            URLPART2="releases/download/v10"
-            ISO="cbpp-10.1-amd64-20190713.iso"
-            ;;
-        11)
-            URLPART2="releases/download/v11.2"
-            ISO="cbpp-11.2-amd64-20230514.iso"
-            ;;
-        12)
-            URLPART2="releases/download/v12.0"
-            ISO="cbpp-12.0-amd64-20230611.iso"
-            ;;
+      8)
+        URLPART2="releases/download/v1.0-amd64"
+        ISO="cbpp-1.0-amd64-20150428.iso"
+        ;;
+      9)
+        URLPART2="9-amd64/releases/download/v9.0"
+        ISO="cbpp-9.0-amd64-20170621.iso"
+        ;;
+      10)
+        URLPART2="releases/download/v10"
+        ISO="cbpp-10.1-amd64-20190713.iso"
+        ;;
+      11)
+        URLPART2="releases/download/v11.2"
+        ISO="cbpp-11.2-amd64-20230514.iso"
+        ;;
+      12)
+        URLPART2="releases/download/v12.0"
+        ISO="cbpp-12.0-amd64-20230611.iso"
+        ;;
     esac
     URL="${URLPART}/${URLPART2}"
     echo "${URL}/${ISO} ${HASH}"
@@ -1984,11 +1984,11 @@ function get_deepin() {
     local URL="https://cdimage.deepin.com/releases/"${RELEASE}
     # fix iso name
     if [[ "${RELEASE}" == *"20" ]] ; then
-      EDITION="1003"
-      ISO="deepin-desktop-community-${EDITION}-amd64.iso"
+        EDITION="1003"
+        ISO="deepin-desktop-community-${EDITION}-amd64.iso"
     elif [[ "${RELEASE}" == *"20.1" ]]; then
-      EDITION="1010"
-      ISO="deepin-desktop-community-${EDITION}-amd64.iso"
+        EDITION="1010"
+        ISO="deepin-desktop-community-${EDITION}-amd64.iso"
     fi
     HASH=$(web_pipe "${URL}/SHA256SUMS" | grep "${ISO}" | cut_1)
     #echo "${URL}/${ISO} ${HASH}"
@@ -2106,26 +2106,26 @@ function get_freedos() {
     local ISO=""
     local URL="http://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/${RELEASE}/official"
     case ${RELEASE} in
-        1.2)
-          ISO="FD12CD.iso"
-          HASH=$(web_pipe "${URL}/FD12.sha" | grep "${ISO}" | cut_1)
-          ;;
-        1.3)
-          ISO="FD13-LiveCD.zip"
-          HASH=$(web_pipe "${URL}/verify.txt" | grep -A 8 "sha256sum" | grep "${ISO}" | cut_1)
-          ;;
+      1.2)
+        ISO="FD12CD.iso"
+        HASH=$(wget -q -O- "${URL}/FD12.sha" | grep "${ISO}" | cut_1)
+        ;;
+      1.3)
+        ISO="FD13-LiveCD.zip"
+        HASH=$(wget -q -O- "${URL}/verify.txt" | grep -A 8 "sha256sum" | grep "${ISO}" | cut_1)
+        ;;
     esac
     echo "${URL}/${ISO} ${HASH}"
 }
 
 function get_garuda() {
-  local EDITION="${1:-}"
-  local HASH=""
-  local ISO=""
-  local URL="https://iso.builds.garudalinux.org/iso/latest/garuda"
-  ISO=${EDITION}/latest.iso
-  HASH="$(web_pipe "${URL}/${ISO}.sha256" | cut_1)"
-  echo "${URL}/${ISO} ${HASH}"
+    local EDITION="${1:-}"
+    local HASH=""
+    local ISO=""
+    local URL="https://iso.builds.garudalinux.org/iso/latest/garuda"
+    ISO=${EDITION}/latest.iso
+    HASH="$(wget -q -O- "${URL}/${ISO}.sha256" | cut_1)"
+    echo "${URL}/${ISO} ${HASH}"
 }
 
 function get_gentoo() {
@@ -2265,43 +2265,43 @@ function get_macos() {
     local OS_TYPE="default"
 
     case ${RELEASE} in
-        lion)           #10.7
-            BOARD_ID="Mac-2E6FAB96566FE58C"
-            MLB="00000000000F25Y00";;
-        mountainlion)   #10.8
-            BOARD_ID="Mac-7DF2A3B5E5D671ED"
-            MLB="00000000000F65100";;
-        mavericks)      #10.9
-            BOARD_ID="Mac-F60DEB81FF30ACF6"
-            MLB="00000000000FNN100";;
-        yosemite)       #10.10
-            BOARD_ID="Mac-E43C1C25D4880AD6"
-            MLB="00000000000GDVW00";;
-        elcapitan)      #10.11
-            BOARD_ID="Mac-FFE5EF870D7BA81A"
-            MLB="00000000000GQRX00";;
-        sierra)         #10.12
-            BOARD_ID="Mac-77F17D7DA9285301"
-            MLB="00000000000J0DX00";;
-        high-sierra)    #10.13
-            BOARD_ID="Mac-BE088AF8C5EB4FA2"
-            MLB="00000000000J80300";;
-        mojave)         #10.14
-            BOARD_ID="Mac-7BA5B2DFE22DDD8C"
-            MLB="00000000000KXPG00";;
-        catalina)       #10.15
-            BOARD_ID="Mac-00BE6ED71E35EB86";;
-        big-sur)        #11
-            BOARD_ID="Mac-42FD25EABCABB274";;
-        monterey)       #12
-            BOARD_ID="Mac-E43C1C25D4880AD6";;
-        ventura)        #13
-            BOARD_ID="Mac-BE088AF8C5EB4FA2";;
-        sonoma)
-            BOARD_ID="Mac-53FDB3D8DB8CA971";;
-        *) echo "ERROR! Unknown release: ${RELEASE}"
-           releases_macos
-           exit 1;;
+      lion)           #10.7
+        BOARD_ID="Mac-2E6FAB96566FE58C"
+        MLB="00000000000F25Y00";;
+      mountainlion)   #10.8
+        BOARD_ID="Mac-7DF2A3B5E5D671ED"
+        MLB="00000000000F65100";;
+      mavericks)      #10.9
+        BOARD_ID="Mac-F60DEB81FF30ACF6"
+        MLB="00000000000FNN100";;
+      yosemite)       #10.10
+        BOARD_ID="Mac-E43C1C25D4880AD6"
+        MLB="00000000000GDVW00";;
+      elcapitan)      #10.11
+        BOARD_ID="Mac-FFE5EF870D7BA81A"
+        MLB="00000000000GQRX00";;
+      sierra)         #10.12
+        BOARD_ID="Mac-77F17D7DA9285301"
+        MLB="00000000000J0DX00";;
+      high-sierra)    #10.13
+        BOARD_ID="Mac-BE088AF8C5EB4FA2"
+        MLB="00000000000J80300";;
+      mojave)         #10.14
+        BOARD_ID="Mac-7BA5B2DFE22DDD8C"
+        MLB="00000000000KXPG00";;
+      catalina)       #10.15
+        BOARD_ID="Mac-00BE6ED71E35EB86";;
+      big-sur)        #11
+        BOARD_ID="Mac-42FD25EABCABB274";;
+      monterey)       #12
+        BOARD_ID="Mac-E43C1C25D4880AD6";;
+      ventura)        #13
+        BOARD_ID="Mac-BE088AF8C5EB4FA2";;
+      sonoma)
+        BOARD_ID="Mac-53FDB3D8DB8CA971";;
+      *) echo "ERROR! Unknown release: ${RELEASE}"
+        releases_macos
+        exit 1;;
     esac
 
     CWD="$(dirname "${0}")"
