Add suport for aria2c for faster downloading if installed

diff --git a/quickget b/quickget
--- a/quickget
+++ b/quickget
@@ -452,9 +452,16 @@ function web_get() {
       exit 1
     fi
 
-    if ! wget --quiet --continue --show-progress --progress=bar:force:noscroll "${URL}" -O "${DIR}/${FILE}"; then
-        echo "ERROR! Failed to download ${URL}. Try running 'quickget' again."
-        exit 1
+    if command -v aria2c > /dev/null; then
+        if ! aria2c -x16 --continue=true --summary-interval=0 --download-result=hide --console-log-level=error "${URL}" -o "${DIR}/${FILE}"; then
+          echo "ERROR! Failed to download ${URL}. Try running 'quickget' again."
+          exit 1
+        fi
+    else 
+        if ! wget --quiet --continue --show-progress --progress=bar:force:noscroll "${URL}" -O "${DIR}/${FILE}"; then
+          echo "ERROR! Failed to download ${URL}. Try running 'quickget' again."
+          exit 1
+        fi
     fi
 }
 
