Add error_unsupported_combination function

diff --git a/quickget b/quickget
--- a/quickget
+++ b/quickget
@@ -260,15 +260,19 @@ function error_not_supported_argument() {
     exit 1
 }
 
+function error_unsupported_combination() {
+    echo "ERROR! Unsupported combination"
+}
+
 function handle_missing() {
     # Handle odd missing Fedora combinations
     case "${OS}" in
-        fedora)
-            if [[ "${RELEASE}" -lt 40 && "${EDITION}" == "Onyx" ]] || [[ "${RELEASE}" -lt 40 && "${EDITION}" == "Sericea" ]]; then
-                echo "ERROR! Unsupported combination"
-                echo "       Fedora ${RELEASE} ${EDITION} is not available, please choose another Release or Edition"
-                exit 1
-            fi;;
+      fedora)
+        if [[ "${RELEASE}" -lt 40 && "${EDITION}" == "Onyx" ]] || [[ "${RELEASE}" -lt 40 && "${EDITION}" == "Sericea" ]]; then
+            error_unsupported_combination
+            echo "       Fedora ${RELEASE} ${EDITION} is not available, please choose another Release or Edition"
+            exit 1
+        fi;;
     esac
 }
 
