run repair hopefully
Signed-off-by: zenobit <zenobit@disroot.org>

diff --git a/quickget b/quickget
--- a/quickget
+++ b/quickget
@@ -3588,43 +3588,43 @@ if [ -n "${2}" ]; then
         EDITION=${EDITIONS[0]}
         if [ -n "${3}" ]; then
             EDITION="${3}"
-                if [[ ! " ${EDITIONS[*]} " =~ " ${EDITION} " ]]; then
-        echo -e "ERROR! ${EDITION} is not a supported $(pretty_name "${OS}") edition."
-        echo -n ' - Editions: '
-        for EDITION in "${EDITIONS[@]}"; do
-            echo -n "${EDITION} "
-        done
-        echo ''
-        exit 1
+            if [[ ! " ${EDITIONS[*]} " =~ " ${EDITION} " ]]; then
+                echo -e "ERROR! ${EDITION} is not a supported $(pretty_name "${OS}") edition."
+                echo -n ' - Editions: '
+                for EDITION in "${EDITIONS[@]}"; do
+                    echo -n "${EDITION} "
+                done
+                echo ''
+                exit 1
+            fi
+        else
+            echo -en "ERROR! You must specify an edition.\n - Editions: "
+            #TODO ERROR here
+            "editions_${OS}"
+            exit 1
         fi
-    else
-        echo -en "ERROR! You must specify an edition.\n - Editions: "
-        #TODO ERROR here
-        "editions_${OS}"
-        exit 1
-    fi
 
-    # Handle odd missing Fedora combinations
-    if [[ $OS == fedora ]] ; then
-        if [[ ${RELEASE} = "33" && ${EDITION} = "i3" ]] || [[ ${RELEASE} = "34" && ${EDITION} = "Cinnamon" ]] || [[ "${RELEASE}" < "39" && ${EDITION} = "Onyx" ]]; then
-            echo "ERROR! Unsupported combination"
-            echo "       Fedora ${RELEASE} ${EDITION} is not available, please choose another Release or Edition"
-            exit 1;
+        # Handle odd missing Fedora combinations
+        if [[ $OS == fedora ]] ; then
+            if [[ ${RELEASE} = "33" && ${EDITION} = "i3" ]] || [[ ${RELEASE} = "34" && ${EDITION} = "Cinnamon" ]] || [[ "${RELEASE}" < "39" && ${EDITION} = "Onyx" ]]; then
+                echo "ERROR! Unsupported combination"
+                echo "       Fedora ${RELEASE} ${EDITION} is not available, please choose another Release or Edition"
+                exit 1;
+            fi
         fi
-    fi
 
-    # Handle missing Manjaro Sway minimal
-    if [[ $OS == manjaro ]] ; then
-        if [[ ${RELEASE} == "sway" && ${EDITION} == "minimal" ]] ; then
-            echo "ERROR! Unsupported combination"
-            echo "       Manjaro Sway does not have a minimal edition"
-            exit 1;
+        # Handle missing Manjaro Sway minimal
+        if [[ $OS == manjaro ]] ; then
+            if [[ ${RELEASE} == "sway" && ${EDITION} == "minimal" ]] ; then
+                echo "ERROR! Unsupported combination"
+                echo "       Manjaro Sway does not have a minimal edition"
+                exit 1;
+            fi
         fi
-    fi
 
-    VM_PATH="${OS}-${RELEASE}-${EDITION}"
-    create_vm "$("get_${OS}" "${EDITION}")"
-    if [ "${OS}" == "macos" ]; then
+        VM_PATH="${OS}-${RELEASE}-${EDITION}"
+        create_vm "$("get_${OS}" "${EDITION}")"
+    elif [ "${OS}" == "macos" ]; then
         # macOS doesn't use create_vm()
         validate_release releases_macos
         get_macos
