arguments == 1
Signed-off-by: zenobit <zenobit@disroot.org>

diff --git a/quickget b/quickget
--- a/quickget
+++ b/quickget
@@ -1145,7 +1145,7 @@ function check_hash() {
     local iso=""
     local hash=""
     local hash_algo=""
-    if [ "${download_iso}" == "on" ]; then
+    if [ "${download_iso}" == 1 ]; then
         iso="${1}"
     else
         iso="${VM_PATH}/${1}"
@@ -1193,13 +1193,14 @@ function web_get() {
     done
 
     # Test mode for ISO
-    if [ "${show_iso_url}" == 'on' ]; then
+    if [ "${show_iso_url}" == 1 ]; then
         echo "${URL}"
         exit 0
-    elif [ "${test_iso_url}" == 'on' ]; then
-        wget --spider "${URL}"
+    elif [ "${test_iso_url}" == 1 ]; then
+        echo -n "Testing if $(echo ${URL} | rev | cut -d'/' -f1 | rev) is available... "
+        wget -q --spider "${URL}" && echo 'Sucessfull' || echo 'ERROR!'
         exit 0
-    elif [ "${download_iso}" == 'on' ]; then
+    elif [ "${download_iso}" == 1 ]; then
         DIR="$(pwd)"
     fi
 
@@ -1237,10 +1238,10 @@ function zsync_get() {
     local URL="${1}"
 
     # Test mode for ISO
-    if [ "${show_iso_url}" == 'on' ]; then
+    if [ "${show_iso_url}" == 1 ]; then
         echo "${URL}"
         exit 0
-    elif [ "${test_iso_url}" == 'on' ]; then
+    elif [ "${test_iso_url}" == 1 ]; then
         wget --spider "${URL}"
         exit 0
     elif command -v zsync &>/dev/null; then
@@ -1283,7 +1284,7 @@ function make_vm_config() {
     local GUEST=""
     local SEC_BOOT=""
 
-    if [ "${download_iso}" == "on" ]; then
+    if [ "${download_iso}" == 1 ]; then
         exit 0
     fi
 
@@ -2107,14 +2108,14 @@ function get_macos() {
     local chunkListLink=$(echo "$info" | grep 'oscdn' | grep 'chunklist')
     local chunkListSession=$(echo "$info" | grep 'expires' | grep 'chunklist')
 
-    if [ "${show_iso_url}" == 'on' ]; then
+    if [ "${show_iso_url}" == 1 ]; then
         echo -e "Recovery URL (inaccessible through normal browser):\n${downloadLink}\nChunklist (used for verifying the Recovery Image):\n${chunkListLink}\nFirmware URLs:\n${OpenCore_qcow2}\n${OVMF_CODE}\n${OVMF_VARS}"
         exit 0
-    elif [ "${test_iso_url}" == 'on' ]; then
+    elif [ "${test_iso_url}" == 1 ]; then
         wget --spider --header "Host: oscdn.apple.com" --header "Connection: close" --header "User-Agent: InternetRecovery/1.0" --header "Cookie: AssetToken=${downloadSession}" "${downloadLink}"
         wget --spider --header "Host: oscdn.apple.com" --header "Connection: close" --header "User-Agent: InternetRecovery/1.0" --header "Cookie: AssetToken=${chunkListSession}" "${chunkListLink}"
         exit 0
-    elif [ "${download_iso}" == 'on' ]; then
+    elif [ "${download_iso}" == 1 ]; then
         echo "Downloading macOS ${RELEASE} from ${downloadLink}"
         web_get "${downloadLink}" "${VM_PATH}" RecoveryImage.dmg --header "Host: oscdn.apple.com" --header "Connection: close" --header "User-Agent: InternetRecovery/1.0" --header "Cookie: AssetToken=${downloadSession}"
         curl --progress-bar "${chunkListLink}" -o RecoveryImage.chunklist --header "Host: oscdn.apple.com" --header "Connection: close" --header "User-Agent: InternetRecovery/1.0" --header "Cookie: AssetToken=${chunkListSession}"
@@ -3217,7 +3218,7 @@ function download_windows() {
     fi
 
     if echo "$iso_download_link_html" | grep -q "We are unable to complete your request at this time."; then
-        if [ "${show_iso_url}" == 'on' ] || [ "${test_iso_url}" == 'on' ]; then
+        if [ "${show_iso_url}" == 1 ] || [ "${test_iso_url}" == 1 ]; then
             echo " - Failed to get URL: Microsoft blocked the automated download request based on your IP address."
             exit 1
         fi
@@ -3244,10 +3245,10 @@ function download_windows() {
         return 1
     fi
 
-    if [ "${show_iso_url}" == 'on' ]; then
+    if [ "${show_iso_url}" == 1 ]; then
         echo -e "   Windows ${RELEASE} Download (valid for 24 hours):\n${iso_download_link}"
         exit 0
-    elif [ "${test_iso_url}" == 'on' ]; then
+    elif [ "${test_iso_url}" == 1 ]; then
         wget --spider "${iso_download_link}"
         exit 0
     fi
@@ -3273,7 +3274,7 @@ function get_windows() {
         download_windows "${RELEASE}"
     fi
 
-    if [ "${download_iso}" == 'on' ]; then
+    if [ "${download_iso}" == 1 ]; then
         exit 0
     fi
 
