set tabs to 4 space

diff --git a/quickemu b/quickemu
--- a/quickemu
+++ b/quickemu
@@ -1724,20 +1724,20 @@ else
 fi
 
 if [ -n "${VM}" ] && [ -e "${VM}" ]; then
-  # shellcheck source=/dev/null
-  source "${VM}"
-  if [ -z "${disk_img}" ]; then
-    echo "ERROR! No disk_img defined."
-    exit 1
-  fi
+    # shellcheck source=/dev/null
+    source "${VM}"
+    if [ -z "${disk_img}" ]; then
+        echo "ERROR! No disk_img defined."
+        exit 1
+    fi
 
-  DiskChkMsg="$("$QEMU_IMG" check -q "${disk_img}" 2>&1)"
+    DiskChkMsg="$("$QEMU_IMG" check -q "${disk_img}" 2>&1)"
 
-  if [[ $DiskChkMsg ]]; then
-    echo; echo "ERROR! disk.qcow2 has problems. Try qemu-img check --help."
-    echo; echo "$DiskChkMsg" ; echo
-    exit 1
-  fi
+    if [[ $DiskChkMsg ]]; then
+        echo; echo "ERROR! disk.qcow2 has problems. Try qemu-img check --help."
+        echo; echo "$DiskChkMsg" ; echo
+        exit 1
+    fi
 
     VMDIR=$(dirname "${disk_img}")
     VMNAME=$(basename "${VM}" .conf)
