feat: Add os_supported_release function

diff --git a/quickget b/quickget
--- a/quickget
+++ b/quickget
@@ -3786,6 +3786,15 @@ fi
 
 LANGS=()
 
+os_supported_release() {
+    if [[ ! " ${RELEASES[*]} " =~ " ${RELEASE} " ]]; then
+        echo -e "ERROR! ${DISPLAY_NAME} ${RELEASE} is not a supported release."
+        echo -n 'Supported releases: '
+        "releases_${OS}"
+        exit 1
+    fi
+}
+
 os_supported_edition() {
     if [[ ! " ${EDITIONS[*]} " =~ " ${EDITION} " ]]; then
         echo -e "ERROR! ${EDITION} is not a supported $(pretty_name "${OS}") edition\n"
