feat: Add function to show error message if OS not specified

diff --git a/quickget b/quickget
--- a/quickget
+++ b/quickget
@@ -3443,6 +3443,14 @@ fi
 
 LANGS=()
 
+os_error() {
+    echo "ERROR! You must specify an operating system."
+    echo "- Supported Operating Systems:"
+    os_support | fold -s -w "$(tput cols)"
+    echo -e "\nTo see all possible arguments, use:\n   quickget -h  or  quickget --help"
+    exit 1
+}
+
 if [ -n "${1}" ]; then
     OS="${1,,}"
     if [ "${OS}" == "list" ] || [ "${OS}" == "list_csv" ]; then
